

from fastapi import (
    FastAPI,
    Request,
    status,
    Response,
)
from fastapi.responses import StreamingResponse
import uvicorn
import time
from dog import Dog

app = FastAPI()
dog = Dog()

@app.get("/status/connected")
async def get_battery_status():
    global dog
    isConnected = dog.check_connection()
    return {"isConnected": isConnected}

@app.get("/status/battery")
async def get_battery_status():
    global dog
    return {"battery_soc": dog.get_soc()}

@app.get("/status/current")
async def get_battery_status():
    global dog
    dog.get_current()
    return {"battery_current": dog.get_current()}

@app.get("/status")
async def get_battery_status():
    global dog
    return {
        "battery_current": dog.get_current(),
        "battery_soc": dog.get_soc(),
        "isConnected": dog.check_connection()}


@app.post("/connect")
async def connect(ip_address: str = "192.168.4.199"):
    global dog
    dog = Dog(ip_address=ip_address)
    
    for _ in range(3):
        time.sleep(1)
        if dog.check_connection():
            return Response(status_code=status.HTTP_200_OK)

    return Response(status_code=status.HTTP_408_REQUEST_TIMEOUT)
    
def generate_cat_picture():
    """
    Generate a cat picture as a byte stream.
    """
    # Simulate generating a cat picture
    time.sleep(1)
    with open("cat.png", "rb") as f:
        image_bytes = f.read()
    return image_bytes
    

@app.get(
    "/raw_image",

    # Set what the media type will be in the autogenerated OpenAPI specification.
    # fastapi.tiangolo.com/advanced/additional-responses/#additional-media-types-for-the-main-response
    responses = {
        200: {
            "content": {"image/png": {}}
        }
    },

    # Prevent FastAPI from adding "application/json" as an additional
    # response media type in the autogenerated OpenAPI specification.
    # https://github.com/tiangolo/fastapi/issues/3258
    response_class=Response
)
def get_image():
    image_bytes: bytes = generate_cat_picture()
    # media_type here sets the media type of the actual response sent to the client.
    return Response(content=image_bytes, media_type="image/png")




if __name__ == "__main__":
    uvicorn.run("DogAPI:app", host="127.0.0.1", port=8000, reload=True)
